### ISSUE TITLE
a bug about multi-allele variants records in v0.3 non-psyche vcf 

### ISSUE THREAD

**Issue by yujin2011** [konradjk/exac_browser#250]
Hi,

I just came across an error when trying to normalize and split the multi-allele variants using bcftools.

here are comments from Shane MC.
```
Looks like this is not a completely valid VCF. They AC_Het tag is Number=A, but some positions have more than the expected number of records.

INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:13404
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:13528
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:17478
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:69521
INFO/AC_Het is Number=A in header. Expected 3, but found 6 at: 1:69552
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:138829
INFO/AC_Het is Number=A in header. Expected 2, but found 3 at: 1:138909
```

According to vcf specification, "Number=A"  implies it equals to the number of alternate allele(n_alt). but actually it should be (n_alt^2+n_alt)/2. 

Thanks,
Jin

**Comment by konradjk** [comment]
This has now been fixed in release 0.3.1: ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1

Indeed it's closer to Number=(G-A) but since no such thing exists, we have made it Number=.

**Comment by yujin2011** [comment]
Hi Konrad,

The new 0.3.1 release seems still crash the bcftools' normalization and allele splitting function.

error message as following:
~~~~~~~~~~~~~
bcftools: vcfnorm.c:414: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
Aborted (core dumped)
~~~~~~~~~~~~~

I can get around this problem by tweaking AC_het = "." in the ExAC's vcf header, but the normalization function will not split the "Het genotype count" correctly for the multiallele variants. 

Best,
Jin
